/// Conversation engine helpers (ADR-0023). Pure Dart.
///
/// The dialogue itself is generated by the vendor-blind tutor
/// (AiChatModel); this file owns the deterministic pieces: picking a
/// scenario, and scoring how well a learner held up in a turn so the
/// `conversationAbility` signal can move.
library;

import 'entities.dart';
import 'relationships.dart';

/// The scenario a conversation should run in: prefer one whose concept
/// the learner is weak at, else the first available.
String? pickScenarioConceptId(
  LanguageKnowledgeGraph graph, {
  Set<String> weakConceptIds = const {},
}) {
  final scenarios = [
    for (final n in graph.nodes.values)
      if (n.tier == LanguageTier.conversation) n,
  ]..sort((a, b) => a.conceptId.compareTo(b.conceptId));
  if (scenarios.isEmpty) return null;
  for (final s in scenarios) {
    // A scenario is "relevant" when a weak concept feeds it (prerequisite
    // or graph relation).
    final relevant = s.prerequisites.any(weakConceptIds.contains) ||
        graph.touching(s.conceptId).any(
              (r) => weakConceptIds.contains(r.from) ||
                  weakConceptIds.contains(r.to),
            );
    if (relevant) return s.conceptId;
  }
  return scenarios.first.conceptId;
}

/// 0..1 quality of a learner's conversational turn: rewards fuller
/// replies and using the target vocabulary the tutor is steering toward.
/// Accent-insensitive so a recognizer / quick typist isn't penalized.
double conversationTurnQuality(String reply, List<String> targetVocab) {
  final words = reply.trim().split(RegExp(r'\s+')).where((w) => w.isNotEmpty);
  if (words.isEmpty) return 0;
  // Length: a couple of words is a start, six-plus is a full sentence.
  var q = (words.length / 6).clamp(0.2, 1.0);
  final said = _fold(reply);
  final usedVocab = targetVocab.any((v) => said.contains(_fold(v)));
  if (usedVocab) q = (q + 0.25).clamp(0.0, 1.0);
  return q;
}

String _fold(String s) {
  const map = {
    'á': 'a', 'é': 'e', 'í': 'i', 'ó': 'o', 'ú': 'u', 'ü': 'u', 'ñ': 'n',
  };
  final buf = StringBuffer();
  for (final ch in s.toLowerCase().split('')) {
    buf.write(map[ch] ?? ch);
  }
  return buf.toString();
}
